import test from 'node:test';
import assert from 'node:assert/strict';
import {inquiryUpdates,isInquiryCategory,publicInquiry,internalInquiry,parseInquiry,isTestInquiry} from './inquiry-tickets';
import {normalizeInquiryMessage} from './inquiry-message';
import type {InquiryTicket} from './inquiry-tickets';
test('five statuses preserve the jobs lifecycle and old API aliases',()=>{assert.deepEqual(inquiryUpdates({status:'answered'}),{inquiry_status:'answered',status:'open'});assert.deepEqual(inquiryUpdates({status:'resolved'}),{inquiry_status:'closed',status:'done'});assert.deepEqual(inquiryUpdates({status:'unresolved'}),{inquiry_status:'new',status:'open'});assert.throws(()=>inquiryUpdates({status:'sent'}));});
test('category is separate from job category',()=>{assert.deepEqual(inquiryUpdates({category:'warranty'}),{inquiry_category:'warranty'});for(const value of ['ads_created','__proto__',null,12])assert.equal(isInquiryCategory(value),false);});
test('bot cannot overwrite identity or original message through status endpoint',()=>{for(const key of ['id','email','customer_email','details','created_by'])assert.throws(()=>inquiryUpdates({[key]:'value'}));});
test('notes and test flag validation',()=>{assert.deepEqual(inquiryUpdates({notes:' Waiting for photos '}),{next_step:'Waiting for photos'});assert.throws(()=>inquiryUpdates({notes:'x'.repeat(10001)}));assert.throws(()=>inquiryUpdates({is_test:'false'}));});
test('API lifecycle round trip',()=>{const row={id:'1',category:'customer_inquiry',status:'open',inquiry_status:'waiting_on_customer',inquiry_category:'warranty',next_step:'Waiting',created_at:'2026-10-08T01:00:00Z'} as InquiryTicket;const api=publicInquiry(row);assert.equal(api.status,'waiting_on_customer');assert.equal(internalInquiry(api).inquiry_status,'waiting_on_customer');assert.equal(internalInquiry(api).status,'open');assert.equal(publicInquiry({...row,status:'done',inquiry_status:undefined}).status,'closed');});
test('form labels parse independently and hide absent order',()=>{const parsed=parseInquiry('Topic: Choosing a sofa\nOrder: Not provided\nCan I get peach?\n\n— Webflow inquiry —\nForm: Contact\nPage: https://luun.ca/contact\nWebflow submission: abc');assert.equal(parsed.topic,'Choosing a sofa');assert.equal(parsed.order,null);assert.equal(parsed.body,'Can I get peach?');assert.deepEqual(parsed.metadata[1],{label:'Page',value:'https://luun.ca/contact'});assert.equal(parseInquiry('Topic: Delivery\nOrder: #123\nWhere is it?').order,'#123');assert.equal(parseInquiry('Topic: SofasOrder: Not providedCan I get peach?').body,'Can I get peach?');});
test('test detection avoids false positives in latest or testimonial',()=>{assert.ok(isTestInquiry('Luun test',null));assert.ok(isTestInquiry(null,'TEST ONLY — checking'));assert.ok(isTestInquiry('Testing inquiry',null));assert.equal(isTestInquiry('Latest customer','I read your testimonials'),false);});
test('Gmail import validates direction, dates and thread ID',()=>{const row={from_email:'TEAM@LUUN.CA',to_email:'customer@example.com',body:'Reply',provider_message_id:'gmail:1',gmail_thread_id:'12345678abcdef',sent_at:'2026-10-01T01:00:00Z'};assert.equal(normalizeInquiryMessage(row).direction,'outbound');assert.equal(normalizeInquiryMessage({...row,from_email:row.to_email,to_email:row.from_email}).direction,'inbound');assert.throws(()=>normalizeInquiryMessage({...row,gmail_thread_id:'javascript:alert(1)'}));assert.throws(()=>normalizeInquiryMessage({...row,from_email:'another@example.com'}));assert.throws(()=>normalizeInquiryMessage({...row,sent_at:'bad'}));});

test('Grok can attach a Gmail conversation link and status in one update',()=>{const url='https://mail.google.com/mail/u/4/#inbox/FMfcExample';assert.deepEqual(inquiryUpdates({gmail_thread_url:url,status:'answered'}),{gmail_thread_url:url,inquiry_status:'answered',status:'open'});for(const value of ['javascript:alert(1)','https://example.com/mail/#x','https://mail.google.com/'])assert.throws(()=>inquiryUpdates({gmail_thread_url:value}));});
